apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: eventbus
  description: The event bus for the eShop application.
spec:
  type: message-queue
  owner: guests
  system: eshop-messaging
  domain: messaging
