apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: webapp
  description: The main web application for the eShop.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: eshop-admin
  lifecycle: experimental
  system: eshop-web
  domain: eshop
  consumesApis:
    - basket-api
    - catalog-api
    - identity-api
    - ordering-api
  dependsOn:
    - component:basket-api
    - component:catalog-api
    - component:identity-api
    - component:ordering-api
